DELETE FROM public.reviews;

INSERT INTO public.reviews (id, name, city, service, rating, comment, created_at)
VALUES
  (gen_random_uuid(), 'Camila R.', 'Santiago', 'Arquitectura TI', 5, 'La verdad partí escéptica porque ya había probado otros consultores. Acá fue distinto: me sentaron a ordenar mi negocio paso a paso. Hoy tengo dominio propio, correo corporativo y un sistema que funciona. No me imaginaba llegar tan lejos.', now() - interval '45 days'),
  (gen_random_uuid(), 'Valentina N.', 'Valparaíso', 'Inteligencia Artificial Corporativa', 5, 'Implementamos un agente que ya está atendiendo a mis clientes mientras duermo, jajaja. Yo no sabía nada de IA y ahora lo administro sola. Cero magia, todo aplicado a mi negocio.', now() - interval '38 days'),
  (gen_random_uuid(), 'Sebastián M.', 'Rancagua', 'Soporte TI Gestionado', 5, 'Lo que más valoro es que me entregaron SLA desde el día uno y me enseñan a entender lo que pasa. Ya no dependo del técnico de turno. Mi PyME funciona como reloj.', now() - interval '52 days'),
  (gen_random_uuid(), 'Felipe V.', 'Concepción', 'Arquitectura TI', 4, 'Muy buena la implementación, quedé con todo ordenado en la nube y los respaldos automáticos. Le bajo una estrella porque me hubiese gustado más material descargable para repasar.', now() - interval '29 days'),
  (gen_random_uuid(), 'Diego C.', 'Punta Arenas', 'Ciberseguridad', 4, 'Aprendí harto: 2FA en todas mis cuentas, gestor de contraseñas, cómo detectar phishing. Marcos da ejemplos reales que se quedan grabados. Faltó profundizar un poco más en respaldo en la nube, pero igual súper útil.', now() - interval '33 days'),
  (gen_random_uuid(), 'Catalina H.', 'Temuco', 'Reducción de Costos TI', 4, 'Necesitaba resolver un tema con licencias viejas y PCs lentas. En una sola sesión quedó claro cuánto podía ahorrar. Fue puntual y al grano, justo lo que buscaba.', now() - interval '21 days'),
  (gen_random_uuid(), 'Rodrigo P.', 'Antofagasta', 'Dirección de Marketing Digital', 3, 'El dashboard de campañas me sirve mucho para ver métricas, pero me costó conectar todo con mi CRM. Llegué a buen puerto pero igual sentí que necesitaba una sesión extra. Como servicio está bueno.', now() - interval '18 days'),
  (gen_random_uuid(), 'Andrea L.', 'Iquique', 'Presencia Digital', 3, 'Buena experiencia en general, mi sitio está publicado y mis redes ordenadas. Lo que sí, me hubiese gustado avanzar más rápido en la parte de SEO técnico, pero entiendo que eso ya es otra etapa.', now() - interval '14 days'),
  (gen_random_uuid(), 'José M.', 'La Serena', 'Transformación Digital', 3, 'La hoja de ruta quedó clara y el equipo entendió el nuevo flujo de trabajo. Igual la implementación tomó una semana más de lo esperado. Bien, pero con margen de mejora en los plazos.', now() - interval '10 days');